In [53]:
import pandas as pd

In [54]:
airbnblisting_df = pd.read_csv("train.csv")

In [55]:
airbnblisting_df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [56]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [57]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Group 2_Airbnb_ Listing/archive/AirbnbLocation.csv"

In [58]:
# Load the CSV file into a Pandas DataFrame
locations_df = pd.read_csv("Airbnb_Location.csv")
locations_df.head()

   City_ID           City          State Country      Lat       Lng
0        1  New York City       New York      US  40.7128   74.0060
1        2   San Franciso     California      US  37.7749  122.4194
2        3     Washington             DC      US  38.9072   77.0369
3        4    Los Angeles     California      US  34.0522  118.2432
4        5         Boston  Massachusetts      US  42.3601   71.0589

In [59]:
# Iterate through the hotel DataFrame 
for index, row in locations_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

In [60]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = locations_df[["Lat", "Lng"]]

In [62]:
# Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(60.8, 45.0), zoom_level=3.75)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)