In [57]:
import pandas as pd

In [58]:
airbnb_df = pd.read_csv("train.csv")

In [59]:
pd.options.display.max_columns = None

In [60]:
airbnb_df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,description,first_review,host_has_profile_pic,host_identity_verified,host_response_rate,host_since,instant_bookable,last_review,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,"Beautiful, sunlit brownstone 1-bedroom in the ...",2016-06-18,t,t,NaN,2012-03-26,f,2016-07-18,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,NYC,Enjoy travelling during your stay in Manhattan...,2017-08-05,t,f,100%,2017-06-19,t,2017-09-23,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,The Oasis comes complete with a full backyard ...,2017-04-30,t,t,100%,2016-10-25,t,2017-09-14,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,SF,This light-filled home-away-from-home is super...,NaN,t,t,NaN,2015-04-19,f,NaN,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,DC,"Cool, cozy, and comfortable studio located in ...",2015-05-12,t,t,100%,2015-03-01,t,2017-01-22,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [61]:
airbnb_df_2 = airbnb_df.drop(columns=["description","name","thumbnail_url"])
airbnb_df_2

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,first_review,host_has_profile_pic,host_identity_verified,host_response_rate,host_since,instant_bookable,last_review,latitude,longitude,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,2016-06-18,t,t,NaN,2012-03-26,f,2016-07-18,40.696524,-73.991617,Brooklyn Heights,2,100.0,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,NYC,2017-08-05,t,f,100%,2017-06-19,t,2017-09-23,40.766115,-73.989040,Hell's Kitchen,6,93.0,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,2017-04-30,t,t,100%,2016-10-25,t,2017-09-14,40.808110,-73.943756,Harlem,10,92.0,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,SF,NaN,t,t,NaN,2015-04-19,f,NaN,37.772004,-122.431619,Lower Haight,0,NaN,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,DC,2015-05-12,t,t,100%,2015-03-01,t,2017-01-22,38.925627,-77.034596,Columbia Heights,4,40.0,20009,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,14549287,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,NYC,NaN,t,t,NaN,2013-03-24,f,NaN,40.709025,-73.939405,Williamsburg,0,NaN,11206.0,1.0,1.0
74107,13281809,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2.0,Real Bed,moderate,True,LA,2016-08-15,t,f,100%,2016-05-03,f,2017-04-15,33.871549,-118.396053,Hermosa Beach,16,93.0,90254,2.0,4.0
74108,18688039,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,NYC,2015-01-03,t,t,100%,2012-01-05,t,2017-09-10,40.706749,-73.942377,Williamsburg,43,94.0,11206.0,2.0,2.0
74109,17045948,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,NYC,NaN,t,f,100%,2017-09-17,t,NaN,40.738535,-74.000157,West Village,0,NaN,10011,0.0,2.0
74110,3534845,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1.0,Real Bed,moderate,False,LA,2013-09-05,t,t,100%,2012-11-26,f,2017-04-30,33.761096,-118.192409,Long Beach,205,96.0,90802,1.0,2.0

In [62]:
airbnb_df_2.to_csv("airbnb_df.csv", index=False)

In [63]:
airbnb_df_2["neighbourhood"]= airbnb_df_2["neighbourhood"].str.replace("'"," ")
#ny_data['has_pool']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'pool'))
#.str.replace('{', '')

In [64]:
ny_data = airbnb_df[airbnb_df["city"]=="NYC"]

In [65]:
ny_data.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,description,first_review,host_has_profile_pic,host_identity_verified,host_response_rate,host_since,instant_bookable,last_review,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,NYC,"Beautiful, sunlit brownstone 1-bedroom in the ...",2016-06-18,t,t,NaN,2012-03-26,f,2016-07-18,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,NYC,Enjoy travelling during your stay in Manhattan...,2017-08-05,t,f,100%,2017-06-19,t,2017-09-23,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,NYC,The Oasis comes complete with a full backyard ...,2017-04-30,t,t,100%,2016-10-25,t,2017-09-14,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
10,5578513,4.605170,Apartment,Private room,"{Internet,""Wireless Internet"",""Air conditionin...",2,1.0,Real Bed,strict,True,NYC,This is a bright bedroom in an historic buildi...,2013-04-28,t,t,100%,2013-03-27,f,2016-11-15,40.723883,-73.983880,Large East Village Bedroom To Let!,Alphabet City,82,93.0,https://a0.muscache.com/im/pictures/21726900/1...,10009.0,1.0,1.0
18,17589436,4.882802,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",2,1.0,Real Bed,strict,True,NYC,"I am renting a very spacious, unique, bright L...",2015-09-26,t,t,71%,2015-08-17,f,2016-12-12,40.719086,-73.990285,"Amazing LES apt - cool, bright...",Lower East Side,26,86.0,NaN,10002,1.0,2.0

In [66]:
all_amenities=ny_data['amenities'].str.replace('{', '').str.replace('}', '').str.replace('"', '').str.cat(sep=',')
amenities_list=all_amenities.split(',')
amenities_dict={}
for each_amenity in amenities_list: 
    if each_amenity in amenities_dict: 
        amenities_dict[each_amenity]+=1
    else: 
        amenities_dict[each_amenity]=1
amenities_dict

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.

{'Wireless Internet': 31304,
 'Air conditioning': 27159,
 'Kitchen': 30068,
 'Heating': 29523,
 'Family/kid friendly': 13582,
 'Essentials': 27561,
 'Hair dryer': 17451,
 'Iron': 16552,
 'translation missing: en.hosting_amenity_50': 11306,
 'Washer': 12375,
 'Dryer': 12223,
 'Smoke detector': 25768,
 'Fire extinguisher': 10123,
 'Shampoo': 19071,
 'Hangers': 20225,
 'TV': 20765,
 'Cable TV': 8641,
 'Breakfast': 3012,
 'Buzzer/wireless intercom': 11979,
 'Carbon monoxide detector': 19438,
 'Laptop friendly workspace': 17637,
 'Internet': 17541,
 'Pets allowed': 3533,
 'Wheelchair accessible': 1956,
 'Elevator': 9027,
 'Lock on bedroom door': 8138,
 'Private entrance': 2347,
 'Hot water': 2771,
 'Bed linens': 2702,
 'Extra pillows and blankets': 1975,
 'Microwave': 2437,
 'Refrigerator': 3010,
 'Dishes and silverware': 2756,
 'Cooking basics': 2634,
 'Oven': 2603,
 'Stove': 2702,
 'Smoking allowed': 1440,
 'Pets live on this property': 3265,
 'Dog(s)': 1351,
 'translation missing: en.hosting_amenity_49': 9255,
 'Free parking on premises': 3134,
 'First aid kit': 10124,
 'Safety card': 3923,
 'Outlet covers': 194,
 'Bathtub': 1740,
 'Coffee maker': 2207,
 'Dishwasher': 1268,
 'Single level home': 360,
 'Luggage dropoff allowed': 1091,
 'Step-free access': 1509,
 'Wide clearance to bed': 297,
 'Accessible-height bed': 254,
 'Wide doorway': 742,
 'Accessible-height toilet': 204,
 'Wide entryway': 219,
 'Hot water kettle': 116,
 '24-hour check-in': 5870,
 'Indoor fireplace': 1229,
 'Gym': 2355,
 'Doorman': 2904,
 'Hot tub': 1456,
 'Self Check-In': 3538,
 'Lockbox': 2046,
 'Cat(s)': 1432,
 'Wide hallway clearance': 349,
 'Flat': 290,
 ' smooth pathway to front door': 290,
 'Well-lit path to entrance': 555,
 '': 198,
 'Host greets you': 987,
 'Pool': 361,
 'Ethernet connection': 460,
 'Long term stays allowed': 1086,
 'Fixed grab bars for shower & toilet': 53,
 'Room-darkening shades': 773,
 'Private living room': 1506,
 'Changing table': 90,
 'High chair': 238,
 'Stair gates': 99,
 'Children’s books and toys': 469,
 'Window guards': 531,
 'Table corner guards': 43,
 'Babysitter recommendations': 344,
 'Crib': 209,
 'Children’s dinnerware': 246,
 'Other': 180,
 'Game console': 230,
 'Suitable for events': 1443,
 'Firm mattress': 83,
 'Smart lock': 336,
 'Pocket wifi': 165,
 'Garden or backyard': 574,
 'Patio or balcony': 625,
 'Baby monitor': 59,
 'Fireplace guards': 54,
 'Pack ’n Play/travel crib': 355,
 'Keypad': 769,
 'Cleaning before checkout': 210,
 'Other pet(s)': 87,
 'Waterfront': 94,
 'Ground floor access': 18,
 'EV charger': 26,
 'Wide clearance to shower & toilet': 87,
 'BBQ grill': 329,
 'Beach essentials': 64,
 'Handheld shower head': 86,
 'Bathtub with shower chair': 27,
 'Baby bath': 125,
 'Lake access': 11,
 'Private bathroom': 33,
 'Beachfront': 21,
 'Air purifier': 12,
 'Disabled parking spot': 14,
 'Ski in/Ski out': 6,
 'Free parking on street': 14,
 'Washer / Dryer': 11,
 'Roll-in shower with chair': 1}

In [67]:
def sort_dict_by_value(d, reverse = False):
    return dict(sorted(d.items(), key = lambda x: x[1], reverse = reverse))

sort_dict_by_value(amenities_dict, reverse=True)

{'Wireless Internet': 31304,
 'Kitchen': 30068,
 'Heating': 29523,
 'Essentials': 27561,
 'Air conditioning': 27159,
 'Smoke detector': 25768,
 'TV': 20765,
 'Hangers': 20225,
 'Carbon monoxide detector': 19438,
 'Shampoo': 19071,
 'Laptop friendly workspace': 17637,
 'Internet': 17541,
 'Hair dryer': 17451,
 'Iron': 16552,
 'Family/kid friendly': 13582,
 'Washer': 12375,
 'Dryer': 12223,
 'Buzzer/wireless intercom': 11979,
 'translation missing: en.hosting_amenity_50': 11306,
 'First aid kit': 10124,
 'Fire extinguisher': 10123,
 'translation missing: en.hosting_amenity_49': 9255,
 'Elevator': 9027,
 'Cable TV': 8641,
 'Lock on bedroom door': 8138,
 '24-hour check-in': 5870,
 'Safety card': 3923,
 'Self Check-In': 3538,
 'Pets allowed': 3533,
 'Pets live on this property': 3265,
 'Free parking on premises': 3134,
 'Breakfast': 3012,
 'Refrigerator': 3010,
 'Doorman': 2904,
 'Hot water': 2771,
 'Dishes and silverware': 2756,
 'Bed linens': 2702,
 'Stove': 2702,
 'Cooking basics': 2634,
 'Oven': 2603,
 'Microwave': 2437,
 'Gym': 2355,
 'Private entrance': 2347,
 'Coffee maker': 2207,
 'Lockbox': 2046,
 'Extra pillows and blankets': 1975,
 'Wheelchair accessible': 1956,
 'Bathtub': 1740,
 'Step-free access': 1509,
 'Private living room': 1506,
 'Hot tub': 1456,
 'Suitable for events': 1443,
 'Smoking allowed': 1440,
 'Cat(s)': 1432,
 'Dog(s)': 1351,
 'Dishwasher': 1268,
 'Indoor fireplace': 1229,
 'Luggage dropoff allowed': 1091,
 'Long term stays allowed': 1086,
 'Host greets you': 987,
 'Room-darkening shades': 773,
 'Keypad': 769,
 'Wide doorway': 742,
 'Patio or balcony': 625,
 'Garden or backyard': 574,
 'Well-lit path to entrance': 555,
 'Window guards': 531,
 'Children’s books and toys': 469,
 'Ethernet connection': 460,
 'Pool': 361,
 'Single level home': 360,
 'Pack ’n Play/travel crib': 355,
 'Wide hallway clearance': 349,
 'Babysitter recommendations': 344,
 'Smart lock': 336,
 'BBQ grill': 329,
 'Wide clearance to bed': 297,
 'Flat': 290,
 ' smooth pathway to front door': 290,
 'Accessible-height bed': 254,
 'Children’s dinnerware': 246,
 'High chair': 238,
 'Game console': 230,
 'Wide entryway': 219,
 'Cleaning before checkout': 210,
 'Crib': 209,
 'Accessible-height toilet': 204,
 '': 198,
 'Outlet covers': 194,
 'Other': 180,
 'Pocket wifi': 165,
 'Baby bath': 125,
 'Hot water kettle': 116,
 'Stair gates': 99,
 'Waterfront': 94,
 'Changing table': 90,
 'Other pet(s)': 87,
 'Wide clearance to shower & toilet': 87,
 'Handheld shower head': 86,
 'Firm mattress': 83,
 'Beach essentials': 64,
 'Baby monitor': 59,
 'Fireplace guards': 54,
 'Fixed grab bars for shower & toilet': 53,
 'Table corner guards': 43,
 'Private bathroom': 33,
 'Bathtub with shower chair': 27,
 'EV charger': 26,
 'Beachfront': 21,
 'Ground floor access': 18,
 'Disabled parking spot': 14,
 'Free parking on street': 14,
 'Air purifier': 12,
 'Lake access': 11,
 'Washer / Dryer': 11,
 'Ski in/Ski out': 6,
 'Roll-in shower with chair': 1}

In [68]:
amenities_type=list(amenities_dict.keys())
amenities_type_price={}
for each_amenity in amenities_type: 
    # each_amenity=amenities_type[0]
    amenities_type_price[each_amenity]=ny_data[ny_data['amenities'].str.contains(each_amenity)]['log_price'].mean()
    
amenities_type_price

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """

{'Wireless Internet': 4.721595155139393,
 'Air conditioning': 4.779690663803625,
 'Kitchen': 4.732433521412895,
 'Heating': 4.737167110226136,
 'Family/kid friendly': 4.956388059567028,
 'Essentials': 4.726582627257077,
 'Hair dryer': 4.789257142530715,
 'Iron': 4.778088165230573,
 'translation missing: en.hosting_amenity_50': 4.558325164866552,
 'Washer': 4.862159112962818,
 'Dryer': 4.869536554953579,
 'Smoke detector': 4.733188569228169,
 'Fire extinguisher': 4.7639179518680415,
 'Shampoo': 4.781238870565657,
 'Hangers': 4.729399160750997,
 'TV': 4.852576325373715,
 'Cable TV': 4.984469358072617,
 'Breakfast': 4.706748932991778,
 'Buzzer/wireless intercom': 4.8104780326180965,
 'Carbon monoxide detector': 4.761377447970387,
 'Laptop friendly workspace': 4.762428047288888,
 'Internet': 4.720751141053069,
 'Pets allowed': 4.815241918810173,
 'Wheelchair accessible': 5.003211681397305,
 'Elevator': 4.901585054835116,
 'Lock on bedroom door': 4.527983441116116,
 'Private entrance': 4.941526209904224,
 'Hot water': 4.750485243868033,
 'Bed linens': 4.763471615474377,
 'Extra pillows and blankets': 4.82383951625078,
 'Microwave': 4.777340377600818,
 'Refrigerator': 4.78088136505086,
 'Dishes and silverware': 4.811119260852243,
 'Cooking basics': 4.816195021166236,
 'Oven': 4.824169467224025,
 'Stove': 4.809654438416809,
 'Smoking allowed': 4.548831025372915,
 'Pets live on this property': 4.53457200320866,
 'Dog(s)': nan,
 'translation missing: en.hosting_amenity_49': 4.492030631490778,
 'Free parking on premises': 4.586278515127024,
 'First aid kit': 4.700456890196349,
 'Safety card': 4.803062640969356,
 'Outlet covers': 4.949082438465,
 'Bathtub': 4.959888213248954,
 'Coffee maker': 4.857952191061239,
 'Dishwasher': 5.052021345666021,
 'Single level home': 4.805924309053482,
 'Luggage dropoff allowed': 4.705394730376253,
 'Step-free access': 4.78306654810949,
 'Wide clearance to bed': 4.778338770210803,
 'Accessible-height bed': 4.696622764047806,
 'Wide doorway': 4.802664807096817,
 'Accessible-height toilet': 4.651508923137263,
 'Wide entryway': 4.802006958078905,
 'Hot water kettle': 4.751963035167774,
 '24-hour check-in': 4.859948317208181,
 'Indoor fireplace': 5.152128347516917,
 'Gym': 5.047624079719555,
 'Doorman': 5.159285385780928,
 'Hot tub': 4.7613847174374655,
 'Self Check-In': 4.869984859049746,
 'Lockbox': 4.828389111373714,
 'Cat(s)': nan,
 'Wide hallway clearance': 4.792529528904301,
 'Flat': 4.84662575357493,
 ' smooth pathway to front door': 4.84662575357493,
 'Well-lit path to entrance': 4.770675298058771,
 '': 4.719340076596487,
 'Host greets you': 4.549793488864459,
 'Pool': 5.092694190921045,
 'Ethernet connection': 4.975326373970634,
 'Long term stays allowed': 4.729928613767564,
 'Fixed grab bars for shower & toilet': 4.639567428879276,
 'Room-darkening shades': 4.965556156142946,
 'Private living room': 4.506849221684101,
 'Changing table': 5.1501982533269155,
 'High chair': 5.2138882450021535,
 'Stair gates': 5.283044325969145,
 'Children’s books and toys': 5.094567392996245,
 'Window guards': 4.853512521598841,
 'Table corner guards': 5.346267562042397,
 'Babysitter recommendations': 5.116683889778936,
 'Crib': 5.375854345715286,
 'Children’s dinnerware': 5.158331943654692,
 'Other': 4.686209840960102,
 'Game console': 4.936677592136961,
 'Suitable for events': 5.056530823639985,
 'Firm mattress': 4.757259231114728,
 'Smart lock': 4.796225448753601,
 'Pocket wifi': 4.846624762109289,
 'Garden or backyard': 4.83156034844623,
 'Patio or balcony': 4.925332249520806,
 'Baby monitor': 5.173538064528089,
 'Fireplace guards': 5.311030681261264,
 'Pack ’n Play/travel crib': 5.2966840130148825,
 'Keypad': 4.720201020037553,
 'Cleaning before checkout': 4.7729866464833925,
 'Other pet(s)': nan,
 'Waterfront': 4.719190783365432,
 'Ground floor access': 4.8500783884827765,
 'EV charger': 4.9847590529464165,
 'Wide clearance to shower & toilet': 4.728068150885432,
 'BBQ grill': 4.921373018326372,
 'Beach essentials': 4.750626256751623,
 'Handheld shower head': 4.679808597529097,
 'Bathtub with shower chair': 4.839090954136186,
 'Baby bath': 5.065444713736185,
 'Lake access': 4.452184019780289,
 'Private bathroom': 4.774254930307817,
 'Beachfront': 4.444717189549345,
 'Air purifier': 4.490325335226383,
 'Disabled parking spot': 4.860109164621476,
 'Ski in/Ski out': 4.408460806369988,
 'Free parking on street': 4.407897498497716,
 'Washer / Dryer': 4.968844497278041,
 'Roll-in shower with chair': 5.010635294096256}

In [69]:
sort_dict_by_value(amenities_type_price, reverse=True)

{'Dog(s)': nan,
 'Indoor fireplace': 5.152128347516917,
 'Dishwasher': 5.052021345666021,
 'Wheelchair accessible': 5.003211681397305,
 'Cable TV': 4.984469358072617,
 'Bathtub': 4.959888213248954,
 'Family/kid friendly': 4.956388059567028,
 'Outlet covers': 4.949082438465,
 'Private entrance': 4.941526209904224,
 'Elevator': 4.901585054835116,
 'Dryer': 4.869536554953579,
 'Washer': 4.862159112962818,
 '24-hour check-in': 4.859948317208181,
 'Coffee maker': 4.857952191061239,
 'TV': 4.852576325373715,
 'Oven': 4.824169467224025,
 'Extra pillows and blankets': 4.82383951625078,
 'Cooking basics': 4.816195021166236,
 'Pets allowed': 4.815241918810173,
 'Dishes and silverware': 4.811119260852243,
 'Buzzer/wireless intercom': 4.8104780326180965,
 'Stove': 4.809654438416809,
 'Single level home': 4.805924309053482,
 'Safety card': 4.803062640969356,
 'Wide doorway': 4.802664807096817,
 'Wide entryway': 4.802006958078905,
 'Hair dryer': 4.789257142530715,
 'Step-free access': 4.78306654810949,
 'Shampoo': 4.781238870565657,
 'Refrigerator': 4.78088136505086,
 'Air conditioning': 4.779690663803625,
 'Wide clearance to bed': 4.778338770210803,
 'Iron': 4.778088165230573,
 'Microwave': 4.777340377600818,
 'Fire extinguisher': 4.7639179518680415,
 'Bed linens': 4.763471615474377,
 'Laptop friendly workspace': 4.762428047288888,
 'Carbon monoxide detector': 4.761377447970387,
 'Hot water kettle': 4.751963035167774,
 'Hot water': 4.750485243868033,
 'Heating': 4.737167110226136,
 'Smoke detector': 4.733188569228169,
 'Kitchen': 4.732433521412895,
 'Hangers': 4.729399160750997,
 'Essentials': 4.726582627257077,
 'Wireless Internet': 4.721595155139393,
 'Internet': 4.720751141053069,
 'Breakfast': 4.706748932991778,
 'Luggage dropoff allowed': 4.705394730376253,
 'First aid kit': 4.700456890196349,
 'Accessible-height bed': 4.696622764047806,
 'Accessible-height toilet': 4.651508923137263,
 'Free parking on premises': 4.586278515127024,
 'translation missing: en.hosting_amenity_50': 4.558325164866552,
 'Smoking allowed': 4.548831025372915,
 'Pets live on this property': 4.53457200320866,
 'Lock on bedroom door': 4.527983441116116,
 'translation missing: en.hosting_amenity_49': 4.492030631490778,
 'Cat(s)': nan,
 'Crib': 5.375854345715286,
 'Table corner guards': 5.346267562042397,
 'Fireplace guards': 5.311030681261264,
 'Pack ’n Play/travel crib': 5.2966840130148825,
 'Stair gates': 5.283044325969145,
 'High chair': 5.2138882450021535,
 'Baby monitor': 5.173538064528089,
 'Doorman': 5.159285385780928,
 'Children’s dinnerware': 5.158331943654692,
 'Changing table': 5.1501982533269155,
 'Babysitter recommendations': 5.116683889778936,
 'Children’s books and toys': 5.094567392996245,
 'Pool': 5.092694190921045,
 'Self Check-In': 4.869984859049746,
 'Other pet(s)': nan,
 'Baby bath': 5.065444713736185,
 'Suitable for events': 5.056530823639985,
 'Gym': 5.047624079719555,
 'Roll-in shower with chair': 5.010635294096256,
 'EV charger': 4.9847590529464165,
 'Ethernet connection': 4.975326373970634,
 'Washer / Dryer': 4.968844497278041,
 'Room-darkening shades': 4.965556156142946,
 'Game console': 4.936677592136961,
 'Patio or balcony': 4.925332249520806,
 'BBQ grill': 4.921373018326372,
 'Disabled parking spot': 4.860109164621476,
 'Window guards': 4.853512521598841,
 'Ground floor access': 4.8500783884827765,
 'Flat': 4.84662575357493,
 ' smooth pathway to front door': 4.84662575357493,
 'Pocket wifi': 4.846624762109289,
 'Bathtub with shower chair': 4.839090954136186,
 'Garden or backyard': 4.83156034844623,
 'Lockbox': 4.828389111373714,
 'Smart lock': 4.796225448753601,
 'Wide hallway clearance': 4.792529528904301,
 'Private bathroom': 4.774254930307817,
 'Cleaning before checkout': 4.7729866464833925,
 'Well-lit path to entrance': 4.770675298058771,
 'Hot tub': 4.7613847174374655,
 'Firm mattress': 4.757259231114728,
 'Beach essentials': 4.750626256751623,
 'Long term stays allowed': 4.729928613767564,
 'Wide clearance to shower & toilet': 4.728068150885432,
 'Keypad': 4.720201020037553,
 '': 4.719340076596487,
 'Waterfront': 4.719190783365432,
 'Other': 4.686209840960102,
 'Handheld shower head': 4.679808597529097,
 'Fixed grab bars for shower & toilet': 4.639567428879276,
 'Host greets you': 4.549793488864459,
 'Private living room': 4.506849221684101,
 'Air purifier': 4.490325335226383,
 'Lake access': 4.452184019780289,
 'Beachfront': 4.444717189549345,
 'Ski in/Ski out': 4.408460806369988,
 'Free parking on street': 4.407897498497716}

In [70]:
def has_amenity(amenity_list, amenity): 
    if amenity in amenity_list: 
        return True
    else: 
        return False

In [71]:
ny_data['has_pool']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'pool'))

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [72]:
ny_data['has_fireplace']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'indoor fireplace'))

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [73]:
ny_data['has_wifi']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'wireless_internet'))

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [74]:
ny_data['has_kitchen']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'kitchen'))

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [75]:
ny_data['has_dishwasher']=ny_data['amenities'].str.lower().apply(lambda x: has_amenity(x, 'dishwasher'))

C:\Users\zacha\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [76]:
ny_data_cleaned = ny_data[["log_price", 
                           "room_type",
                           "accommodates",
                           "neighbourhood",
                           "zipcode",
                           "bedrooms",
                           "bathrooms", 
                           'review_scores_rating', 
                           'has_pool', 
                           'has_fireplace',
                           'has_wifi',
                           'has_kitchen',
                           'has_dishwasher'
                          ]]

In [77]:
ny_data['has_pool'].value_counts()

False    31988
True       361
Name: has_pool, dtype: int64

In [78]:
ny_data_cleaned.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,Entire home/apt,3,Brooklyn Heights,11201,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,Entire home/apt,7,Hell's Kitchen,10019,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,Entire home/apt,5,Harlem,10027,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,Private room,2,Alphabet City,10009.0,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,Entire home/apt,2,Lower East Side,10002,1.0,1.0,86.0,False,False,False,True,False

In [79]:
ny_data_cleaned.shape[0]

32349

In [80]:
ny_data_cleaned.dropna()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,Entire home/apt,3,Brooklyn Heights,11201,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,Entire home/apt,7,Hell's Kitchen,10019,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,Entire home/apt,5,Harlem,10027,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,Private room,2,Alphabet City,10009.0,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,Entire home/apt,2,Lower East Side,10002,1.0,1.0,86.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74094,3.688879,Private room,2,East Harlem,10035.0,1.0,1.0,86.0,False,False,False,True,False
74096,3.912023,Private room,2,Washington Heights,10032,1.0,1.0,60.0,False,False,False,True,False
74097,4.700480,Private room,2,Chelsea,10011.0,1.0,1.0,92.0,False,False,False,True,False
74100,4.605170,Private room,2,Williamsburg,11211.0,1.0,1.0,93.0,False,False,False,True,False
74108,5.220356,Entire home/apt,5,Williamsburg,11206.0,2.0,1.0,94.0,False,False,False,True,True

In [101]:
ny_data_cleaned.to_csv("ny_data_w_5_amenities.csv", index=False)

In [81]:
ny_data_cleaned.shape[0]

32349

In [82]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [83]:
df2 = ny_data_cleaned.copy()
df2['room_type'] = le.fit_transform(df2['room_type']) 
df2.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,0,3,Brooklyn Heights,11201,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,0,7,Hell's Kitchen,10019,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,0,5,Harlem,10027,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,1,2,Alphabet City,10009.0,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,0,2,Lower East Side,10002,1.0,1.0,86.0,False,False,False,True,False

In [84]:
df3 = df2.copy()
df3['neighbourhood'] = le.fit_transform(df2['neighbourhood']) 
df3.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,0,3,20,11201,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,0,7,88,10019,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,0,5,87,10027,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,1,2,1,10009.0,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,0,2,109,10002,1.0,1.0,86.0,False,False,False,True,False

In [85]:
df4 = df3.copy()
df4['zipcode'] = le.fit_transform(df2['zipcode']) 
df4.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,0,3,20,154,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,0,7,88,33,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,0,5,87,43,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,1,2,1,17,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,0,2,109,4,1.0,1.0,86.0,False,False,False,True,False

In [86]:
df4.dtypes

log_price               float64
room_type                 int32
accommodates              int64
neighbourhood             int32
zipcode                   int32
bedrooms                float64
bathrooms               float64
review_scores_rating    float64
has_pool                   bool
has_fireplace              bool
has_wifi                   bool
has_kitchen                bool
has_dishwasher             bool
dtype: object

In [87]:
df4.isnull().sum()

log_price                  0
room_type                  0
accommodates               0
neighbourhood              0
zipcode                    0
bedrooms                  47
bathrooms                 99
review_scores_rating    7321
has_pool                   0
has_fireplace              0
has_wifi                   0
has_kitchen                0
has_dishwasher             0
dtype: int64

In [88]:
df4.dropna(inplace=True)

In [89]:
df4.isnull().sum()

log_price               0
room_type               0
accommodates            0
neighbourhood           0
zipcode                 0
bedrooms                0
bathrooms               0
review_scores_rating    0
has_pool                0
has_fireplace           0
has_wifi                0
has_kitchen             0
has_dishwasher          0
dtype: int64

In [90]:
df4.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,0,3,20,154,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,0,7,88,33,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,0,5,87,43,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,1,2,1,17,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,0,2,109,4,1.0,1.0,86.0,False,False,False,True,False

df4.isnull()

In [91]:
X = df4.drop("log_price", axis=1)
y= df4["log_price"]

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)

In [93]:
from sklearn.preprocessing import StandardScaler
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [94]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
# reg = LinearRegression().fit(X_train, y_train)
reg = RandomForestRegressor().fit(X_train, y_train)

In [95]:
y_pred = reg.predict(X_test)

In [96]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)

In [97]:
print(mse)

0.13127528910752548

In [98]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

print("R-squared value:", r2)

R-squared value: 0.6876224072297743

In [99]:
df4.to_csv('NY_data_simple.csv', index=False)

In [100]:
df4.head()

,log_price,room_type,accommodates,neighbourhood,zipcode,bedrooms,bathrooms,review_scores_rating,has_pool,has_fireplace,has_wifi,has_kitchen,has_dishwasher
0,5.010635,0,3,20,154,1.0,1.0,100.0,False,False,False,True,False
1,5.129899,0,7,88,33,3.0,1.0,93.0,False,False,False,True,False
2,4.976734,0,5,87,43,1.0,1.0,92.0,False,False,False,True,False
10,4.605170,1,2,1,17,1.0,1.0,93.0,False,False,False,True,False
18,4.882802,0,2,109,4,1.0,1.0,86.0,False,False,False,True,False